= Omniwallet Functional Tests

Browser-based functional testing of Omniwallet. Uses the http://www.gebish.org[Geb] browser automation and the http://spockframework.org[Spock Test Framework]. 

== Prerequisites

* Java JDK 7 or later
* Chrome Browser installed
* Firefox Browser installed

== Running the tests

To run the tests from your desktop, clone this repository and use the Gradle wrapper script to run the tests.

To run tests using Chrome, Firefox, and http://phantomjs.org[PhantomJS] on Mac OS X or Linux.

    ./gradlew test

On Windows, use:

    ./gradlew.bat test

As long as the JDK is correctly installed The Gradle wrapper script will automatically download and install the remaining prerequisites, if necesary, before running the tests.

If you want to run tests with a single browser, replace the Gradle `test` target with `chromeTest`, `firefoxTest`, or `phantomJsTest` respectively.

== CI (Jenkins)

The http://ci.omni.foundation/job/omniwallet-func-test/[omniwallet-func-test job] runs these tests headlessly using PhantomJS.





